---
authors:
  - Ansible Community
license_file: LICENSE
name: utils
namespace: ansible
description:
  Ansible Collection with utilities to ease the management, manipulation,
  and validation of data within a playbook
readme: README.md
repository: https://github.com/ansible-collections/ansible.utils
issues: https://github.com/ansible-collections/ansible.utils/issues
tags:
  - linux
  - networking
  - security
  - cloud
  - utilities
  - data
  - validation
  - utils
version: 4.1.0
