name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [main]
    types:
    - labeled
    - opened
    - reopened
    - synchronize
  workflow_dispatch:

jobs:
  safe-to-test:
    if: >-
      github.event.label.name == 'safe to test' ||
      github.event.action != 'labeled'
    uses: ansible-network/github_actions/.github/workflows/safe-to-test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tox-ansible:
    uses: tox-dev/tox-ansible/.github/workflows/run.yml@main
    needs:
      - safe-to-test

  tox-ansible-passed:
    if: ${{ always() }}
    needs:
      - tox-ansible
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.tox-ansible.result }}',
          ]) == {'success'}"
