name: Test collection

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main

  all_green:
    if: ${{ always() }}
    needs:
      - changelog
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.changelog.result }}',
          ]) == {'success'}"
