name: Test collection
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
  integration:
    uses: ansible-network/github_actions/.github/workflows/integration_simple.yml@main
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
    with:
      matrix_exclude: >-
        [
          {
            "ansible-version": "stable-2.9",
            "python-version": "3.9"
          },
          {
            "ansible-version": "stable-2.9",
            "python-version": "3.10"
          },
          {
            "ansible-version": "stable-2.10",
            "python-version": "3.10"
          },
          {
            "ansible-version": "stable-2.11",
            "python-version": "3.10"
          }
        ]

  unit-galaxy:
    uses: ansible-network/github_actions/.github/workflows/unit_simple.yml@main

  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - integration
      - sanity
      - unit-galaxy
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.changelog.result }}',
          '${{ needs.integration.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}'
          ]) == {'success'}"
